import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "./QueryProvider";
import { Poppins } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          poppins.className + "text-base text-foreground bg-background"
        }
      >
        <QueryProvider> {children}</QueryProvider>
      </body>
    </html>
  );
}
